export const strings = {
  appTitle: 'Tango',
  toggleMenu: '切换菜单',
  errorTitle: '出错了',
  errorOk: '确定',
  connect: {
    availableDevices: '可用设备',
    noDevices: '暂无设备',
    connect: '连接',
    addUsb: '添加 USB 设备',
    disconnect: '断开',
    connectingTitle: '正在连接',
    connectingSub: '请在设备上授权连接',
    webUsbUnsupported:
      '当前浏览器不支持 WebUSB，无法使用本站点。\n\n请使用最新版本的 Google Chrome、Microsoft Edge 或其他基于 Chromium 的浏览器。'
  },
  nav: {
    home: '首页',
    deviceInfo: '设备信息',
    fileManager: '文件管理',
    framebuffer: '屏幕截图',
    install: '安装 APK',
    tcpip: 'ADB over Wi-Fi',
    logcat: 'Logcat',
    power: '电源菜单',
    packetLog: '数据包日志',
    bugReport: 'Bug 报告'
  },
  home: {
    documentTitle: 'Tango',
    introP1: '这是 ya-webadb 的演示，可通过 ADB 协议在 Web 浏览器（或 Node.js）中控制 Android 设备。',
    introP2:
      '项目源于尝试 WebUSB API 与个人使用需求；并非生产就绪，普通用户请谨慎尝试。问题与建议可到 GitHub 提交 issue。',
    introP3: '曾用名 ya-webadb（Yet Another WebADB），因同类项目较简单且维护停滞，故自行实现。',
    linkYaWebadb: 'https://github.com/yume-chan/ya-webadb/',
    linkYaWebadbLabel: 'ya-webadb',
    linkWebUsb: 'https://developer.mozilla.org/en-US/docs/Web/API/USB',
    linkWebUsbLabel: 'WebUSB',
    linkIssues: 'https://github.com/yume-chan/ya-webadb/issues',
    linkIssuesLabel: 'GitHub Issues',
    linkWebadbJs: 'https://github.com/webadb/webadb.js',
    linkWebadbJsLabel: 'webadb.js',
    linkWebadbLiry: 'https://github.com/Liry/WebADB',
    linkWebadbLiryLabel: 'WebADB（Liry）'
  },
  deviceInfo: {
    documentTitle: '设备信息',
    productName: '产品名（ro.product.name）',
    modelName: '型号（ro.product.model）',
    deviceName: '设备名（ro.product.device）',
    productProp: '对应 Android Build Props 字段 ro.product.name',
    modelProp: '对应 Android Build Props 字段 ro.product.model',
    deviceProp: '对应 Android Build Props 字段 ro.product.device',
    featuresIntro: '特性列表决定各命令的行为，例如是否支持新命令或旧缺陷是否已修复。',
    featuresLabel: '特性',
    noDevice: '请先连接设备'
  },
  power: {
    documentTitle: '电源菜单',
    reboot: '重启',
    powerOff: '关机',
    powerButton: '按电源键',
    danger: '下方为危险操作',
    bootloader: '重启到 Bootloader',
    fastboot: '重启到 Fastboot',
    recovery: '重启到 Recovery',
    sideload: '重启到 Sideload',
    edl: '重启到高通 EDL',
    edlHint: '仅部分高通设备可用',
    qualcommTooltip: '仅部分高通设备支持'
  },
  tcpip: {
    documentTitle: 'ADB over Wi-Fi',
    refresh: '刷新',
    apply: '应用',
    wifiHintPrefix: '若要通过无线网络连接设备，通常需要',
    wifiHintLink: 'https://github.com/yume-chan/ya-webadb/discussions/245#discussioncomment-384030',
    wifiHintLinkLabel: '额外环境或工具',
    wifiHintSuffix: '（见讨论说明）。',
    disconnectWarning: '修改 ADB over Wi-Fi 相关配置后，当前连接通常会断开。',
    listenAddrsProp: 'service.adb.listen_addrs',
    tcpPortProp: 'service.adb.tcp.port',
    persistPortProp: 'persist.adb.tcp.port'
  },
  install: {
    documentTitle: '安装 APK',
    bypassLowTarget: '--bypass-low-target-sdk-block（Android 14）',
    browse: '选择 APK',
    stageUploading: '上传中',
    stageInstalling: '安装中',
    stageDone: '完成'
  },
  framebuffer: {
    documentTitle: '屏幕截图',
    capture: '截取',
    save: '保存',
    demoMode: '演示模式',
    infoTooltip: '使用 ADB Framebuffer 命令截取全尺寸、高分辨率截图'
  },
  demoMode: {
    noteTitle: '说明',
    noteBody: '设备可能不支持全部选项。',
    allowed: '允许',
    enabled: '启用'
  },
  fileManager: {
    documentTitle: '文件管理',
    loading: '加载中…',
    previewImageAlt: '预览图',
    kindDir: '目录',
    kindFile: '文件',
    rootCrumb: '设备',
    upload: '上传',
    download: '下载',
    delete: '删除',
    colType: '类型',
    colName: '名称',
    colPerm: '权限',
    colSize: '大小',
    colMtime: '修改时间',
    colCtime: '创建时间',
    colAtime: '访问时间',
    uploadingTitle: '上传中'
  },
  logcat: {
    documentTitle: 'Logcat',
    start: '开始',
    stop: '停止',
    clear: '清空',
    selectAll: '全选',
    copySelected: '复制所选',
    saveSelected: '保存所选',
    formatMenu: '格式',
    formatHeader: '格式',
    modifiersHeader: '修饰符',
    modifierTz: '时区',
    timeHeader: '时间格式',
    timeDefault: '默认',
    nanoHeader: '纳秒精度',
    colTime: '时间',
    colPid: 'PID',
    colTid: 'TID',
    colPri: '级别',
    colTag: 'Tag',
    colMessage: '消息'
  },
  packetLog: {
    documentTitle: '数据包日志',
    clear: '清空',
    selectAll: '全选',
    copy: '复制',
    colDirection: '方向',
    colCommand: '命令',
    colArg0: 'Arg0',
    colArg1: 'Arg1',
    colPayload: '负载'
  },
  bugReport: {
    documentTitle: 'Bug 报告',
    intro: '对应 Android 的 bugReport / bugReports 工具。',
    generateText: '生成 BugReport（文本）',
    generateZipStream: '生成压缩 BugReport（流式）',
    generateZip: '生成压缩 BugReport',
    generating: '生成中，请稍候',
    noProgressHint: '（本机不支持进度回调）',
    progress: '进度',
    noDevice: '请先连接设备'
  }
} as const;
